import { NextResponse } from "next/server"
import { PDFDocument, rgb, StandardFonts } from "pdf-lib"

const GREEN = rgb(0.13, 0.55, 0.35)
const DARK = rgb(0.15, 0.15, 0.18)
const MUTED = rgb(0.4, 0.42, 0.48)
const LIGHT_BG = rgb(0.97, 0.98, 0.97)

type PdfForm = {
  patientName: string
  patientAge: string
  diagnosis: string
  service: string
  doctor: string
  eps: string
}

type PdfResult = {
  caseId: string
  score: number
  approved: boolean
  reasoning: string
  timestamp?: string
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/)
  const lines: string[] = []
  let current = ""

  for (const word of words) {
    const next = current ? `${current} ${word}` : word
    if (next.length > maxChars && current) {
      lines.push(current)
      current = word
    } else {
      current = next
    }
  }
  if (current) lines.push(current)
  return lines
}

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const form = body.form as PdfForm | undefined
    const result = body.result as PdfResult | undefined

    if (!form || !result?.caseId) {
      return NextResponse.json(
        { error: "Se requieren form y result con caseId." },
        { status: 400 },
      )
    }

    const pdf = await PDFDocument.create()
    const page = pdf.addPage([595, 842])
    const { width, height } = page.getSize()
    const font = await pdf.embedFont(StandardFonts.Helvetica)
    const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold)

    let y = height - 48

    page.drawRectangle({
      x: 0,
      y: height - 100,
      width,
      height: 100,
      color: GREEN,
    })

    page.drawText("ClearPath Health", {
      x: 48,
      y: height - 52,
      size: 22,
      font: fontBold,
      color: rgb(1, 1, 1),
    })
    page.drawText("Medical Authorization Report", {
      x: 48,
      y: height - 76,
      size: 12,
      font,
      color: rgb(0.9, 0.95, 0.92),
    })

    y = height - 130

    const timestamp =
      result.timestamp ?? new Date().toLocaleString("es-CO", { timeZone: "America/Bogota" })
    const decision = result.approved ? "AUTO_APROBADO" : "REVISION_HUMANA"

    const fields: [string, string][] = [
      ["Case ID", result.caseId],
      ["Patient Name", form.patientName],
      ["Age", String(form.patientAge)],
      ["Diagnosis", form.diagnosis],
      ["Requested Service", form.service],
      ["Doctor", form.doctor],
      ["EPS", form.eps],
      ["Pertinence Score", `${result.score} / 100`],
      ["Decision", decision],
      ["Timestamp", timestamp],
    ]

    for (const [label, value] of fields) {
      page.drawRectangle({
        x: 48,
        y: y - 4,
        width: width - 96,
        height: 28,
        color: LIGHT_BG,
        borderColor: rgb(0.88, 0.9, 0.88),
        borderWidth: 0.5,
      })
      page.drawText(label, {
        x: 56,
        y: y + 6,
        size: 9,
        font: fontBold,
        color: GREEN,
      })
      page.drawText(value, {
        x: 200,
        y: y + 6,
        size: 10,
        font,
        color: DARK,
        maxWidth: width - 220,
      })
      y -= 36
    }

    y -= 8
    page.drawText("Clinical Reasoning", {
      x: 48,
      y,
      size: 11,
      font: fontBold,
      color: GREEN,
    })
    y -= 18

    const reasoningLines = wrapText(result.reasoning ?? "", 90)
    for (const line of reasoningLines) {
      page.drawText(line, {
        x: 48,
        y,
        size: 10,
        font,
        color: MUTED,
        maxWidth: width - 96,
      })
      y -= 14
      if (y < 80) break
    }

    page.drawLine({
      start: { x: 48, y: 56 },
      end: { x: width - 48, y: 56 },
      thickness: 0.5,
      color: rgb(0.85, 0.87, 0.85),
    })
    page.drawText("Generated by ClearPath Health — UiPath Maestro Authorization Engine", {
      x: 48,
      y: 40,
      size: 8,
      font,
      color: MUTED,
    })

    const pdfBytes = await pdf.save()

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="authorization-${result.caseId}.pdf"`,
      },
    })
  } catch (error) {
    console.error("[Generate PDF Exception]:", error)
    return NextResponse.json({ error: "No se pudo generar el PDF." }, { status: 500 })
  }
}
